### ISSUE TITLE
Directory listing pages' cache should be independently configurable (or deactivable)

### ISSUE THREAD

**Issue by OdyX** [nginx/nginx-s3-gateway#133]
When pushing assets to S3 buckets, the ~index~ **directory listing** pages  as accessed via the nginx-s3-gateway stay cached for quite some time. When relying on the ~index~ **directory listing** pages to watch for most recent content, that kinda defeats the point.

**Comment by zc-devs** [comment]
What's about directory listing? :)

BTW, there is `PROXY_CACHE_VALID_OK` and also we can clear cache.

**Comment by OdyX** [comment]
Yes. I was talking about directory listing, sorry. The problem with `PROXY_CACHE_VALID_OK` is that I want to cache static files from the s3 bucket as long as possible, but not cache the directory listing at all, and `PROXY_CACHE_VALID_OK` applies to both.

**Comment by zc-devs** [comment]
I've just played with configs...

We can just add `proxy_no_cache 1;` in `common/etc/nginx/templates/gateway/s3listing_location.conf.template`, rebuild image and use it.

1. Generated listing pages are not cached, because of `proxy_no_cache` directive in `@s3Listing` location.
2. S3 files are served by `@s3` location and therefore are cached.

**Comment by dekobon** [comment]
Would you consider this issue solved?

**Comment by zc-devs** [comment]
> in Kubernetes via a mounted ConfigMap file

We can use config below:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngs3gw-gw-templates
data:
  s3listing_location.conf.template: |
    proxy_no_cache 1;
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngs3gw
spec:
  template:
    spec:
      containers:
        - name: ngs3gw
          image: nginxinc/nginx-s3-gateway:unprivileged-oss
          volumeMounts:
            - name: templates
              mountPath: /etc/nginx/templates/gateway/s3listing_location.conf.template
              subPath: s3listing_location.conf.template
      volumes:
        - name: templates
          configMap:
            name: ngs3gw-gw-templates
```
